import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The sidebar is generated automatically from the `docs/` structure.
// Ordering of categories and pages is controlled via:
//   - `sidebar_position` in the page frontmatter;
//   - `_category_.json` in the folder (label, position, collapsed, collapsible).
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
